#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d           

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#21222c"
bspc config focused_border_color "#50fa7b"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# autostart

picom -b --experimental-backends --backend glx
betterlockscreen -w
#setxkbmap -model abnt2 -layout br -variant abnt2
~/.config/polybar/launch.sh
